name: Test suite

on: [pull_request]

jobs:
  lint:
    name: Typescript linting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: |
          npm install

    - name: Analysing the code with eslint
      run: |
          npm run lint

  test:
    name: Run Cypress test against mocked APIs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'   

    - name: Install dependencies
      run: |
          npm install

    - name: Execute tests
      run: |
        npm run cy:e2e-headless

    - name: Upload execution screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Screenshots
        path: ./cypress/screenshots

    - name: Cleanup test suite execution
      run: |
        rm -rf ./cypress/screenshots
        rm -rf ./cypress/downloads
